[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rescue_protocol = "GCcUbgthDu323rfq9Z3iWNFR632wXWMZ66KKtdTtxDBT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/lala_02/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
