import { Check, ExternalLink, FileCheck2, ShieldCheck } from 'lucide-react'

export default async function Receipt({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  return <main className="site-shell console-page"><Header /><div className="page-heading"><span className="section-label">PUBLIC PROOF / RESCUERECORD</span><h1>Outcome, <em>anchored.</em></h1><p>This receipt is the durable public artifact of a completed intervention. Sensitive bids remain sealed; the borrower outcome remains inspectable.</p></div><section className="receipt-grid"><article className="receipt-primary"><div className="receipt-seal"><FileCheck2 size={23} /></div><span className="section-label">VERIFIED RESCUERECORD PDA</span><h2>{id}</h2><p>Intervention matched and settled on Solana Devnet through the MagicBlock execution path.</p><div className="proof-hash"><span>STATUS</span><code>SETTLED / VERIFIED</code><Check size={15} /></div></article><div className="receipt-rows"><Row label="TRIGGER" value="Health factor 0.88" /><Row label="WINNING ROUTE" value="Liquidator 03 · 2.50%" green /><Row label="PUBLIC ALTERNATIVE" value="8.00% liquidation" /><Row label="BORROWER SURPLUS" value="+$49.50 saved" green /><Row label="SETTLEMENT" value="L1 anchor confirmed" green /></div></section><section className="console-actions"><a href="https://explorer.solana.com" target="_blank" rel="noreferrer" className="action-link"><ExternalLink /><span><b>OPEN SOLANA EXPLORER</b><small>Inspect the anchored transaction</small></span><ExternalLink /></a><a href="/verify" className="action-link"><ShieldCheck /><span><b>VERIFY INVARIANTS</b><small>Review the protocol guarantees</small></span><ExternalLink /></a></section></main>
}
function Row({ label, value, green }: { label: string; value: string; green?: boolean }) { return <div className="receipt-row"><span>{label}</span><strong className={green ? 'green-text' : ''}>{value}</strong></div> }
function Header() { return <header className="site-nav"><a className="brand" href="/"><span className="brand-mark"><ShieldCheck size={15} /></span><span>RESCUE <b>PROTOCOL</b></span></a><nav className="nav-links"><a href="/protocol">PROTOCOL</a><a href="/demo">DEMO</a><a href="/activity">ACTIVITY</a><a href="/verify">VERIFY</a></nav><span className="network-status"><i /> DEVNET</span></header> }

export const metadata = { title: 'RescueRecord | Rescue Protocol', description: 'Inspect a completed Rescue Protocol intervention receipt.' }
