import { ArrowRight, Check, ExternalLink, LockKeyhole, Radio, ShieldCheck, Siren } from 'lucide-react'

const links = [['/demo', 'RUN DEMO'], ['/activity', 'ACTIVITY'], ['/proof/rescue-record-rp-0427', 'PROOF'], ['/verify', 'VERIFY']]

export default function Home() {
  return <main className="site-shell console-home"><header className="site-nav"><a className="brand" href="/"><span className="brand-mark"><Siren size={15} /></span><span>RESCUE <b>PROTOCOL</b></span></a><nav className="nav-links" aria-label="Protocol navigation">{links.map(([href, label]) => <a href={href} key={href}>{label}</a>)}</nav><span className="network-status"><i /> DEVNET</span></header>
    <section className="console-hero motion-enter"><div><div className="eyebrow"><span className="status-pip" /> MAGICBLOCK-POWERED LIQUIDATION INFRASTRUCTURE</div><h1>Your liquidation is <em>competitive.</em></h1><p className="hero-lede">When a position becomes distressed, Rescue creates a temporary competitive intervention market instead of exposing the borrower to a public liquidation race.</p><div className="hero-actions"><a className="primary-button" href="/demo">RUN THE RESCUE DEMO <ArrowRight size={16} /></a><a className="text-link" href="/activity">INSPECT LIVE ACTIVITY <Radio size={14} /></a></div></div><div className="console-hero-card"><div className="visual-topline"><span>PROTOCOL THESIS / 001</span><span className="visual-live"><i /> OPERATIONAL</span></div><strong className="console-quote">A private moment<br />before public loss.</strong><div className="console-stat-grid"><div><span>SURPLUS PRESERVED</span><b>$49.50</b></div><div><span>EXECUTION</span><b>TEE → SOLANA</b></div><div><span>INTERVENTION</span><b>SEALED BIDS</b></div></div></div></section>
    <section className="console-grid"><article className="console-card"><span className="section-label">THE PROBLEM</span><h2>Public liquidation destroys borrower equity.</h2><p>Keepers race against the same visible state. Rescue inserts a constrained, confidential window where eligible actors compete on the borrower&apos;s behalf.</p></article><article className="console-card accent-card"><span className="section-label">THE PRIMITIVE</span><h2>Delegate. Compete. Commit.</h2><div className="mini-flow"><span>BASE SOLANA</span><ArrowRight /><span>EPHEMERAL ROLLUP</span><ArrowRight /><span>RESCUERECORD</span></div></article></section>
    <section className="console-proof"><div><span className="section-label">THE OUTCOME</span><h2>Less value extracted.<br /><em>More value returned.</em></h2><p>Rescue is not a promise to prevent liquidation. It is a mechanism for making the outcome competitive, bounded, and independently verifiable.</p></div><div className="proof-stat"><span>BORROWER SURPLUS SAVED</span><strong>$49.50</strong><b>2.50% RESCUE PENALTY</b></div></section>
    <section className="console-actions"><a href="/demo" className="action-link"><LockKeyhole /> <span><b>RUN THE DEMO</b><small>Touch the complete intervention lifecycle</small></span><ArrowRight /></a><a href="/proof/rescue-record-rp-0427" className="action-link"><ShieldCheck /> <span><b>VIEW THE PROOF</b><small>Inspect the anchored RescueRecord</small></span><ArrowRight /></a></section>
    <footer className="site-footer"><div className="brand"><span className="brand-mark"><Siren size={15} /></span><span>RESCUE <b>PROTOCOL</b></span></div><p>A competitive intervention primitive for Solana.</p><a href="/verify">JUDGE VERIFICATION <ExternalLink size={13} /></a></footer></main>
}
